name: Build document

on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install asciidoctor asciidoctor-bibtex
      - name: Convert draw.io file to png image
        uses: Burnett01/actions-drawio@1.0
        with:
          src: string.drawio
          dest: string.png
      - run: make
