name: Build document

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install asciidoctor asciidoctor-bibtex
      - run: wget https://github.com/jgraph/drawio-desktop/releases/download/v14.5.1/drawio-amd64-14.5.1.deb
      - run: sudo apt install ./drawio-amd64-14.5.1.deb
      - run: make
